name: Build LPH
on: [push]
jobs:
  build:
    name: Build the app with Angular and NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Genear archivo de configuracion de firebase
        working-directory: lph/src/environments
        run: echo -n -e "${{secrets.FIREBASE_CONFIG}}" > firebase.environment.ts

      - name: Install Dependencies
        working-directory: lph
        run: npm install

      - name: Ejecutar pruebas de unidad
        working-directory: lph
        run: npm run ci:test

      - name: Create Build
        working-directory: lph
        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: "1//05OhMA3ShvtAPCgYIARAAGAUSNwF-L9IrnnDLl3Qs4VTzVzzA5sSN0uRtDVpn1sNdawxm5771zk9N2z4xW722RnYJ2Do0xjPvrDU"
          PROJECT_PATH: lph
